Repository Team-Rocket-nbc-team2/CosmicDetox, pull requests merged in 2024-09, with the labels that each got.

#77 허용 앱 실행 중 다른 앱 접속 감지 및 차단
  app/src/main/java/com/rocket/cosmic_detox/data/model/AllowedApp.kt
  app/src/main/java/com/rocket/cosmic_detox/data/model/CheckedApp.kt
  app/src/main/java/com/rocket/cosmic_detox/data/repository/AllowAppRepositoryImpl.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/component/bottomsheet/TimerAllowedAppBottomSheet.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/component/bottomsheet/adapter/AllowedAppAdapter.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/service/AppMonitorService.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/view/activity/MainActivity.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/view/fragment/mypage/MyPageViewModel.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/view/fragment/timer/TimerFragment.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/viewmodel/AllowedAppViewModel.kt
Labels: enhancement

#85 허용 앱 bottom sheet가 열려 있을 때, bottom sheet를 벗어났을 때의 처리
  app/src/main/java/com/rocket/cosmic_detox/presentation/component/bottomsheet/TimerAllowedAppBottomSheet.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/viewmodel/AllowedAppViewModel.kt
Labels: bug

#92 피드백 적용
  app/src/main/java/com/rocket/cosmic_detox/domain/usecase/timer/GetAllowedAppUseCase.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/component/bottomsheet/TimerAllowedAppBottomSheet.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/viewmodel/AllowedAppViewModel.kt
Labels: enhancement

#101 kakao login 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/rocket/cosmic_detox/data/datasource/season/SeasonDataSource.kt
  app/src/main/java/com/rocket/cosmic_detox/data/datasource/season/SeasonDataSourceImpl.kt
  app/src/main/java/com/rocket/cosmic_detox/data/datasource/user/UserDataSource.kt
  app/src/main/java/com/rocket/cosmic_detox/data/datasource/user/UserDataSourceImpl.kt
  app/src/main/java/com/rocket/cosmic_detox/data/local/.gitkeep
  app/src/main/java/com/rocket/cosmic_detox/data/remote/.gitkeep
  app/src/main/java/com/rocket/cosmic_detox/data/repository/AllowAppRepositoryImpl.kt
  app/src/main/java/com/rocket/cosmic_detox/data/repository/KakaoSignInRepositoryImpl.kt
  app/src/main/java/com/rocket/cosmic_detox/data/repository/MyPageRepositoryImpl.kt
  app/src/main/java/com/rocket/cosmic_detox/data/repository/RaceRepositoryImpl.kt
  app/src/main/java/com/rocket/cosmic_detox/di/AppModule.kt
  app/src/main/java/com/rocket/cosmic_detox/di/FirebaseModule.kt
  app/src/main/java/com/rocket/cosmic_detox/di/RepositoryModule.kt
  app/src/main/java/com/rocket/cosmic_detox/domain/repository/KakaoSignInRepository.kt
  app/src/main/java/com/rocket/cosmic_detox/domain/usecase/kakao/KakaoLoginUseCase.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/CosmicDetoxApplication.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/uistate/LoginUiState.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/view/activity/SignInActivity.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/viewmodel/SignInViewModel.kt
  app/src/main/res/layout/activity_sign_in.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: enhancement

#108 google login refactoring
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/rocket/cosmic_detox/data/repository/AllowAppRepositoryImpl.kt
  app/src/main/java/com/rocket/cosmic_detox/data/repository/KakaoSignInRepositoryImpl.kt
  app/src/main/java/com/rocket/cosmic_detox/data/repository/SignInRepositoryImpl.kt
  app/src/main/java/com/rocket/cosmic_detox/di/AppModule.kt
  app/src/main/java/com/rocket/cosmic_detox/di/RepositoryModule.kt
  app/src/main/java/com/rocket/cosmic_detox/domain/repository/KakaoSignInRepository.kt
  app/src/main/java/com/rocket/cosmic_detox/domain/repository/SignInRepository.kt
  app/src/main/java/com/rocket/cosmic_detox/domain/usecase/kakao/KakaoLoginUseCase.kt
  app/src/main/java/com/rocket/cosmic_detox/domain/usecase/signin/GoogleSignInUseCase.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/view/activity/MainActivity.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/view/activity/SignInActivity.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/viewmodel/SignInViewModel.kt
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: enhancement

#114 로그인 에러 fix
  app/src/main/java/com/rocket/cosmic_detox/data/repository/SignInRepositoryImpl.kt
  app/src/main/java/com/rocket/cosmic_detox/domain/repository/SignInRepository.kt
  app/src/main/java/com/rocket/cosmic_detox/domain/usecase/kakao/KakaoLoginUseCase.kt
  app/src/main/java/com/rocket/cosmic_detox/domain/usecase/signin/GoogleSignInUseCase.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/uistate/LoginUiState.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/view/activity/SignInActivity.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/viewmodel/SignInViewModel.kt
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/values-en/string.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#115 타이머 오류 해결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/rocket/cosmic_detox/presentation/CosmicDetoxApplication.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/receiver/MidnightResetReceiver.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/service/TimerService.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/view/activity/MainActivity.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/viewmodel/PermissionViewModel.kt
Labels: bug

#121 설정 화면 구현
  app/src/main/java/com/rocket/cosmic_detox/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/rocket/cosmic_detox/domain/repository/UserRepository.kt
  app/src/main/java/com/rocket/cosmic_detox/domain/usecase/user/DeleteUserUseCase.kt
  app/src/main/java/com/rocket/cosmic_detox/domain/usecase/user/SignOutUseCase.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/view/activity/MainActivity.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/view/fragment/home/HomeFragment.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/view/fragment/mypage/MyPageFragment.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/view/fragment/mypage/MyPageViewModel.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/view/fragment/settings/SettingsFragment.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/view/fragment/timer/TimerFragment.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/view/fragment/timer/TimerFragment2.kt
  app/src/main/java/com/rocket/cosmic_detox/presentation/viewmodel/UserViewModel.kt
  app/src/main/java/com/rocket/cosmic_detox/util/Constants.kt
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_arrow_right.png
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/drawable/ic_exit.xml
  app/src/main/res/drawable/ic_locked.xml
  app/src/main/res/drawable/ic_note.xml
  app/src/main/res/drawable/ic_remove_circle.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/drawable/ic_warning_circle.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#138 readme 작성
  README.md
Labels: enhancement
